# Site settings
title: the padded cell
email: ba@sanitarium.se
description: ""
baseurl: ""
url: "http://sanitarium.se"
twitter_username: gaqzi
github_username:  gaqzi
facebook_username:
timezone: UTC

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","LICENSE","css/bootstrap.css","css/clean-blog.css","js/bootstrap.js","js/clean-blog.js","js/jquery.js"]
