# Site settings
title: the padded cell
email: ba@sanitarium.se
description: ""
baseurl: ""
url: "http://sanitarium.se"
twitter_username: gaqzi
github_username:  gaqzi
facebook_username:
timezone: UTC
github_base_url: https://github.com/gaqzi/sanitarium.se/blob/master/

# Build settings
markdown: kramdown
redcarpet:
  extensions:
    - footnotes
kramdown:
  input: GFM
  syntax_highlighter: rouge
  hard_wrap: false
highlighter: pygments
permalink: pretty
paginate: 5
paginate_path: /page/:num
exclude:
  - less
  - node_modules
  - Gruntfile.js
  - package.json
  - README.md
  - LICENSE
  - css/bootstrap.css
  - css/clean-blog.css
  - css/syntax.css
  - css/*.min.css
  - js/bootstrap.js
  - js/clean-blog.js
  - js/jquery.js
  - js/bootstrap.min.js
  - js/clean-blog.min.js
  - js/jquery.min.js
